### ISSUE TITLE
About obtaining OSM data

### ISSUE THREAD

**Issue by wowlza** [jike5/P-MapNet#1]
Thanks for your great work! 

  I have a question about obtaining OSM data in the nuScenes dataset:
  I see that the code mainly involves converting from EPSG 3857 to EPSG 4326 to obtain OSM data. However, I found significant deviations in this conversion process in practice, requiring manual adjustments.
For details, please see the following link:  https://github.com/nutonomy/nuscenes-devkit/issues/1011

The coordinate transformation method provided by nuScenes officials is completely different. 
So I wander how do you handle such deviations and get the aligned data?

Thanks!

**Comment by jike5** [comment]
> Thanks for your great work!
> 
> I have a question about obtaining OSM data in the nuScenes dataset: I see that the code mainly involves converting from EPSG 3857 to EPSG 4326 to obtain OSM data. However, I found significant deviations in this conversion process in practice, requiring manual adjustments. For details, please see the following link: [nutonomy/nuscenes-devkit#1011](https://github.com/nutonomy/nuscenes-devkit/issues/1011)
> 
> The coordinate transformation method provided by nuScenes officials is completely different. So I wander how do you handle such deviations and get the aligned data?
> 
> Thanks!

As discussed in the (issue1011)[https://github.com/nutonomy/nuscenes-devkit/issues/1011], I have also tried the (methods)[https://github.com/nutonomy/nuscenes-devkit/issues/1011#issuecomment-1823850973], and the conclusion is that there are still some inconsistencies. However, for our algorithm, such misalignment is acceptable (our SD Prior Module based on cross-attention can cover these misalignments), so we have not made further adjustments to this slight deviation.

**Comment by wowlza** [comment]
@jike5 
Thanks for your reply!
But the visualization of SD map provided in the paper appendix looks well-aligned. So when I tried to get the OSM data by myself, I was very puzzled as to why I got such a large deviation using this method. Here is the comparison between the two images.
![image](https://github.com/jike5/P-MapNet/assets/114270963/e132e4cf-a7d2-443f-8b9e-d3f86ffb22d5)

As you can see,  the results I obtained don't seem to qualify as slight deviations

**Comment by jike5** [comment]
@wowlza In this [image](https://private-user-images.githubusercontent.com/114270963/287508606-a3bf76ac-5e54-48ce-bae3-cbb69e02ae2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTE5NDIsIm5iZiI6MTcxMTA5MTY0MiwicGF0aCI6Ii8xMTQyNzA5NjMvMjg3NTA4NjA2LWEzYmY3NmFjLTVlNTQtNDhjZS1iYWUzLWNiYjY5ZTAyYWUyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwNzE0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2UyMTkwZWQ1NzkxZDI0ZWQ2MzlmOGIyNTk0NWJmMmRkNmVkOGQxZGJlMDQ4NTRlNjdlMjQzNTUxOGE1YWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gwIpja5nP4iO6drgzen52FphMvqFQU0yjn42RBYPSsc), haven't you already aligned it very well?

There is something that needs clarification. In our open-source code, we actually used an affine transformation matrix to correct the Boston map, but this approach is not standard (it can only be considered a temporary solution):

https://github.com/jike5/P-MapNet/blob/2c061ab6d4a695693fb06fcb42c8367d4556a1d5/data_osm/vector_map.py#L82

Later, we found the method mentioned in [link](https://github.com/nutonomy/nuscenes-devkit/issues/1011#issuecomment-1823850973), and we tried it out with great results. However, it has not been integrated into our code yet.
Here is a code snippet we used:

<img width="482" alt="image" src="https://github.com/jike5/P-MapNet/assets/58059573/c353af91-0647-49bd-88b1-f8ceb660853d">

https://github.com/mapillary/OpenSfM/blob/c72419228fb8c86f2c367989abd64f784ec684b3/opensfm/geo.py#L179

**Comment by wowlza** [comment]
@jike5
 I did not conduct transform to correct the boston map, so the deviation was obvious.  I then aligned it following  the [method](https://github.com/nutonomy/nuscenes-devkit/issues/1011#issuecomment-1823850973) .

But I saw the open-source code did not conduct the conversion following the [method](https://github.com/nutonomy/nuscenes-devkit/issues/1011#issuecomment-1823850973). So I was a little curious.

Thanks for your patient reply！

**Comment by ailias** [comment]
> @jike5 I did not conduct transform to correct the boston map, so the deviation was obvious. I then aligned it following the [method](https://github.com/nutonomy/nuscenes-devkit/issues/1011#issuecomment-1823850973) .
> 
> But I saw the open-source code did not conduct the conversion following the [method](https://github.com/nutonomy/nuscenes-devkit/issues/1011#issuecomment-1823850973). So I was a little curious.
> 
> Thanks for your patient reply！

Do you have the plan to write a more efficient code for aligning OSM and Nuscenes map data? Thank you .

**Comment by jike5** [comment]
> > @jike5 I did not conduct transform to correct the boston map, so the deviation was obvious. I then aligned it following the [method](https://github.com/nutonomy/nuscenes-devkit/issues/1011#issuecomment-1823850973) .
> > But I saw the open-source code did not conduct the conversion following the [method](https://github.com/nutonomy/nuscenes-devkit/issues/1011#issuecomment-1823850973). So I was a little curious.
> > Thanks for your patient reply！
> 
> Do you have the plan to write a more efficient code for aligning OSM and Nuscenes map data? Thank you .

Are you talking about using the method in issue1011? Due to some reasons, I can't access the code I've already implemented. I'll try to re-implement it on Wednesday.

**Comment by jike5** [comment]
@ailias Done, https://github.com/jike5/P-MapNet/commit/138c7d389591198d1d054b2075f9525a69b777b5
