### ISSUE TITLE
MapTR-SDMap

### ISSUE THREAD

**Issue by Jun10** [jike5/P-MapNet#2]
Do you have the plan to release the source code for the integration of SDMap prior module into MapTR as mentioned in the paper? Thanks!

**Comment by jike5** [comment]
> Do you have the plan to release the source code for the integration of SDMap prior module into MapTR as mentioned in the paper? Thanks!

The code may have been deleted due to the server subscription expiring😭. We are currently looking to see if there is a corresponding backup available, and if we find one, we will open-source it.
