### ISSUE TITLE
sd_60m result!!

### ISSUE THREAD

**Issue by missTL** [jike5/P-MapNet#3]
Hi, the reproduction result of my post-training test in sd_60m.py is:
![image](https://github.com/jike5/P-MapNet/assets/98095885/d3c4d70f-20d3-4db5-b294-6a7272ee6978)
This is quite different from what is reported in your paper, is the repository profile corresponding to the paper results?

**Comment by jike5** [comment]
> Hi, the reproduction result of my post-training test in sd_60m.py is: ![image](https://private-user-images.githubusercontent.com/98095885/323867755-d3c4d70f-20d3-4db5-b294-6a7272ee6978.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTA4MTcsIm5iZiI6MTcxNzI1MDUxNywicGF0aCI6Ii85ODA5NTg4NS8zMjM4Njc3NTUtZDNjNGQ3MGYtMjBkMy00ZGI1LWIyOTQtNmE3MjcyZWU2OTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE0MDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkY2E0MjIwMDIxM2YxNDI3NjZlMzc2NjliZjkyZjNhYTZiMDE4ZjMzOGRiODM2NDllYWQwMTZkNmE1NzRmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eRDhpCOqj8LfMXn4JbrKQ01etziAB-18SQaGpcHQA7c) This is quite different from what is reported in your paper, is the repository profile corresponding to the paper results?

@Jzian He is carefully checking the issue you mentioned, and we expect to have results soon. We have been busy with other projects recently, so apologies for the wait.

**Comment by Jzian** [comment]
Sorry for the late reply! We have pushed the new [branch](https://github.com/jike5/P-MapNet/tree/60m) and retrained it from scratch, it works fine in the range of 60m with sdmap. The config and log is [here](https://github.com/jike5/P-MapNet/tree/60m/output).
<img src="https://github.com/user-attachments/assets/5f06aa8e-95ca-4f17-aae0-2c4d159a3626" width="30%">
