### ISSUE TITLE
sd_60m.py

### ISSUE THREAD

**Issue by krabs-H** [jike5/P-MapNet#4]
Can you offer the config file when training the sd prior?I coundn't get the result as yours. How many GPUs did you use?Is it 4?

**Comment by jike5** [comment]
> Can you offer the config file when training the sd prior?I coundn't get the result as yours. How many GPUs did you use?Is it 4?

I checked, and the configuration we used was [sd_60m.py](https://github.com/jike5/P-MapNet/blob/dev-1.0/config/nusc/sd_prior/sd_60m.py). We should have used 8*3090 for the experiment. Can you paste your experiment config file so we can confirm it?

**Comment by missTL** [comment]
> Can you offer the config file when training the sd prior?I coundn't get the result as yours. How many GPUs did you use?Is it 4?

Have you got the results in the paper? And how?

**Comment by Jzian** [comment]
Sorry for the late reply! We have pushed the new [branch](https://github.com/jike5/P-MapNet/tree/60m) and retrained it from scratch, it works fine in the range of 60m with sdmap. The config and log is [here](https://github.com/jike5/P-MapNet/tree/60m/output).
<img src="https://github.com/user-attachments/assets/5f06aa8e-95ca-4f17-aae0-2c4d159a3626" width="30%">
