### ISSUE TITLE
The SDmap about Argoverse

### ISSUE THREAD

**Issue by lynn-yu** [jike5/P-MapNet#6]
I can not find 'sd_map_data_{name}.pkl' about Argoverse, Could you please specify it?

**Comment by jike5** [comment]
> I can not find 'sd_map_data_{name}.pkl' about Argoverse, Could you please specify it?

Done, https://github.com/jike5/P-MapNet/commit/934a41f711f1e7e294b50a81b76d0fe238236c5b
