### ISSUE TITLE
SDMap抽取

### ISSUE THREAD

**Issue by night3759** [jike5/P-MapNet#7]
您好，我想请教一下，怎么用OpenStreetMap导出相应的SDmap

**Comment by night3759** [comment]
是使用osmnx库抽取的吗，我抽出来的感觉和你们抽出来的不太一样，想问下具体用的那个函数，万分感谢！

**Comment by jike5** [comment]
> 是使用osmnx库抽取的吗，我抽出来的感觉和你们抽出来的不太一样，想问下具体用的那个函数，万分感谢！

不是，用的是BBBiKE这个网站，直接下载的数据
